//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeSharp.Core.SourceGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeSharp.Core.SourceGenerator.Properties.SourceTemplates", typeof(SourceTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable enable
        ///using Microsoft.Extensions.DependencyInjection;
        ///using Microsoft.Extensions.Options;
        ///using PokeSharp.Core;
        ///using PokeSharp.Core.State;
        ///
        ///namespace {{Namespace}};
        ///
        ///public static class {{ServiceName}}ServiceShortcut 
        ///{
        ///    private static CachedService&lt;{{WrappedType}}&gt; _instance = new();
        ///
        ///    extension(GameGlobal) 
        ///    {
        ///        public static {{ServiceType}} {{ServiceName}} =&gt; _instance.Instance{{AdditionalAccessor}};
        ///    }
        ///}.
        /// </summary>
        internal static string AutoServiceShortcutTemplate {
            get {
                return ResourceManager.GetString("AutoServiceShortcutTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable enable
        ///using System.Diagnostics.CodeAnalysis;
        ///using Microsoft.Extensions.DependencyInjection;
        ///using PokeSharp.Core;
        ///using PokeSharp.Core.Data;
        ///
        ///namespace {{Namespace}};
        ///
        ///partial {{ClassType}} {{ClassName}} : I{{EntityType}}GameDataEntity&lt;{{Key}}, {{ClassName}}&gt; 
        ///{
        ///    private static CachedService&lt;{{EntityType}}GameDataSet&lt;{{ClassName}}, {{Key}}&gt;&gt; _data = new();
        ///
        ///    private static {{EntityType}}GameDataSet&lt;{{ClassName}}, {{Key}}&gt; Data =&gt; _data.Instance;
        ///
        ///    {{#IsLoaded}}
        ///    public [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameDataEntityTemplate {
            get {
                return ResourceManager.GetString("GameDataEntityTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #nullable enable
        ///using PokeSharp.Core.Data;
        ///
        ///namespace {{Namespace}};
        ///
        ///partial class {{ClassName}} : IGameDataProvider&lt;{{EntityType}}&gt; 
        ///{
        ///    int IGameDataProvider&lt;{{EntityType}}&gt;.Priority =&gt; {{Priority}};
        ///
        ///    IEnumerable&lt;{{EntityType}}&gt; IGameDataProvider&lt;{{EntityType}}&gt;.GetEntitiesToRegister()
        ///    {
        ///        {{#HasRegistrations}}
        ///        {{#Registrations}}
        ///        yield return {{Name}};    
        ///        {{/Registrations}}
        ///        {{/HasRegistrations}}
        ///        {{^HasRegistrations}}
        ///        retur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameDataRegistrationTemplate {
            get {
                return ResourceManager.GetString("GameDataRegistrationTemplate", resourceCulture);
            }
        }
    }
}
