//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeSharp.Compiler.SourceGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeSharp.Compiler.SourceGenerator.Properties.SourceTemplates", typeof(SourceTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if ({{Entries}}.Length != {{TypeEntries.Length}})
        ///    throw new SerializationException($&quot;Unexpected number of elements in {value}! Expecting {{#MultipleOf}}a multiple of{{/MultipleOf}}{{TypeEntries.Length}}, got { {{Entries}}.Length}.&quot;);
        ///
        ///{{ResultLineStart}}new {{ParsedType}}(
        ///{{#TypeEntries}}
        ///    {{#Indexed}}{{&gt;ParseLogic OutputOperation=&apos;&apos; Parameter=&apos;splitLine[{{Index}}]&apos;}}{{~^IsLast~}},{{~/IsLast~}}{{/Indexed}}
        ///{{/TypeEntries}}
        ///){{ResultLineEnd}}.
        /// </summary>
        internal static string EvaluateComplexTypeTemplate {
            get {
                return ResourceManager.GetString("EvaluateComplexTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{~#NeedsConversion~}}
        ///Text.Localized(&quot;{{../../../Namespace}}.{{../../../ClassName}}&quot;, $&quot;{sectionName}.{{../../Name}}&quot;, {{&gt;ParseMethodCall}})
        ///{{~/NeedsConversion~}}    
        ///{{~^NeedsConversion~}}
        ///{{&gt;ParseMethodCall}}
        ///{{~/NeedsConversion~}}.
        /// </summary>
        internal static string ParseLogicTemplate {
            get {
                return ResourceManager.GetString("ParseLogicTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{~#NeedsParsing~}}{{ParseMethod}}({{Parameter}}{{#AllowNone}}, true{{/AllowNone}}){{~/NeedsParsing~}}
        ///{{~^NeedsParsing~}}{{Parameter}}{{~/NeedsParsing~}}.
        /// </summary>
        internal static string ParseMethodCallTemplate {
            get {
                return ResourceManager.GetString("ParseMethodCallTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Runtime.Serialization;
        ///using System.Collections.Immutable;
        ///using PokeSharp.Abstractions;
        ///using PokeSharp.Compiler.Core.Serialization;
        ///
        ///namespace {{Namespace}};
        ///
        ///public static class {{ClassName}}Serializer
        ///{
        ///    public static {{ClassName}} ParsePbsData(PbsSection section)
        ///    {
        ///        {{#Properties}}
        ///        {{#IsSectionName}}
        ///        var prop_{{Name}} = Parse_{{Name}}({{#NeedsSectionName}}section.SectionName, {{/NeedsSectionName}}section.SectionName);
        ///        {{/IsSectionName}}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PbsSerializerTemplate {
            get {
                return ResourceManager.GetString("PbsSerializerTemplate", resourceCulture);
            }
        }
    }
}
