//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokeSharp.Compiler.SourceGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokeSharp.Compiler.SourceGenerator.Properties.SourceTemplates", typeof(SourceTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{#NoOptionalParameters}}
        ///if (splitLine.Length != {{TypeEntries.Length}})
        ///    throw new SerializationException($&quot;Unexpected number of elements in {value}! Expecting {{#MultipleOf}}a multiple of {{/MultipleOf}}{{TypeEntries.Length}}, got {splitLine.Length}.&quot;);
        ///{{/NoOptionalParameters}}
        ///{{^NoOptionalParameters}}
        ///if (splitLine.Length &lt; {{RequiredLength}})
        ///    throw new SerializationException($&quot;Unexpected number of elements in {value}! Got {splitLine.Length}, expected at least {{RequiredLength}}&quot;);
        ///
        ///if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EvaluateComplexTypeTemplate {
            get {
                return ResourceManager.GetString("EvaluateComplexTypeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{#IsNullable}}{{#IsValueType}}.Value{{/IsValueType}}{{/IsNullable}}.
        /// </summary>
        internal static string NullableAccessTemplate {
            get {
                return ResourceManager.GetString("NullableAccessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{~#NeedsConversion~}}
        ///Text.Localized(&quot;{{../../../Namespace}}.{{../../../ClassName}}&quot;, $&quot;{sectionName}.{{../../Name}}&quot;, {{&gt;ParseMethodCall}})
        ///{{~/NeedsConversion~}}    
        ///{{~^NeedsConversion~}}
        ///{{&gt;ParseMethodCall}}
        ///{{~/NeedsConversion~}}.
        /// </summary>
        internal static string ParseLogicTemplate {
            get {
                return ResourceManager.GetString("ParseLogicTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{~#NeedsParsing~}}{{ParseMethod}}({{Parameter}}{{#AllowNone}}, true{{/AllowNone}}){{~/NeedsParsing~}}
        ///{{~^NeedsParsing~}}{{Parameter}}{{~/NeedsParsing~}}.
        /// </summary>
        internal static string ParseMethodCallTemplate {
            get {
                return ResourceManager.GetString("ParseMethodCallTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Runtime.Serialization;
        ///using System.Collections.Immutable;
        ///using PokeSharp.Abstractions;
        ///using PokeSharp.Compiler.Core.Serialization;
        ///
        ///namespace {{Namespace}};
        ///
        ///{{DeclaredAccessiblity}}partial {{ObjectType}} {{ClassName}} : IPbsDataModel&lt;{{ClassName}}&gt;
        ///{
        ///    public static string BasePath =&gt; &quot;{{FileName}}&quot;;
        ///    public static bool IsOptional =&gt; {{IsOptionalString}};
        ///
        ///    public static {{ClassName}} ParsePbsData(PbsSection section, Func&lt;string, {{ClassName}}&gt; modelFactory = null)
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PbsSerializerTemplate {
            get {
                return ResourceManager.GetString("PbsSerializerTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{#IsNullable}}
        ///if ({{Name}}{{#IsValueType}}.HasValue{{/IsValueType}}{{^IsValueType}} is not null{{/IsValueType}}{{#HasValidation}} &amp;&amp; {{ValidateMethodName}}({{Name}}{{#IsValueType}}.Value{{/IsValueType}}){{/HasValidation}})
        ///{
        ///    {{#WithIndent &apos;    &apos;}}
        ///    {{&gt;PropertyWrite}}
        ///    {{/WithIndent}}
        ///}
        ///{{/IsNullable}}
        ///{{^IsNullable}}
        ///{{#HasValidation}}
        ///if ({{ValidateMethodName}}({{Name}}))
        ///{
        ///    {{#WithIndent &apos;    &apos;}}
        ///    {{&gt;PropertyWrite}}
        ///    {{/WithIndent}}
        ///}
        ///{{/HasValidation}}
        ///{{^HasValidati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PropertyWriteChecksTemplate {
            get {
                return ResourceManager.GetString("PropertyWriteChecksTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{#AppearsOnce}}
        ///yield return $&quot;{{KeyName}} = {Write_{{Name}}({{Name}}{{&gt;NullableAccess}})}&quot;;
        ///{{/AppearsOnce}}
        ///{{^AppearsOnce}}
        ///foreach (var element in {{Name}}{{&gt;NullableAccess}})
        ///{
        ///    yield return $&quot;{{KeyName}} = {Write_{{Name}}(element)}&quot;;
        ///}
        ///{{/AppearsOnce}}.
        /// </summary>
        internal static string PropertyWriteTemplate {
            get {
                return ResourceManager.GetString("PropertyWriteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{~#HasWriteMethod~}}{{WriteMethod}}({{Value}}){{~/HasWriteMethod~}}   
        ///{{~^HasWriteMethod~}}{{Value}}{{^IsString}}.ToString(){{/IsString}}{{~/HasWriteMethod~}}.
        /// </summary>
        internal static string WriteMethodCallTemplate {
            get {
                return ResourceManager.GetString("WriteMethodCallTemplate", resourceCulture);
            }
        }
    }
}
